version: '3.8'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./outputs:/app/outputs
    environment:
      - ELEVEN_LABS_APIKEY=${ELEVEN_LABS_APIKEY:-}
      - SUPERTONE_APIKEY=${SUPERTONE_APIKEY:-}
      - SKT_A_X_APIKEY=${SKT_A_X_APIKEY:-}
      - VOICEVOX_URL=http://localhost:50021

  # voicevox-engine:
  #   image: voicevox/voicevox_engine:cpu-latest
  #   ports:
  #     - "50021:50021"
  #   networks:
  #     - tts-network
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:50021/version"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 5
  #     start_period: 60s

# networks:
#   tts-network:
#     driver: bridge
